source "${0:A:h}/chezmoi.completion.zsh"

alias cz="chezmoi"
alias cza="chezmoi add"
alias czap="chezmoi apply"
alias czcd="chezmoi cd"
alias czd="chezmoi diff"
alias cze="chezmoi edit"
alias czg="chezmoi git"
alias czrm="chezmoi remove"
alias czst="chezmoi status"
